name: Fetch Daily Quest

on:
  # Atur jadwal otomatis, misalnya setiap 30 menit
  schedule:
    - cron: '*/30 * * * *'
  # Memungkinkan untuk menjalankan workflow secara manual dari GitHub UI
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run DQ fetcher script
        # DISCORD_BOT_TOKEN dan DISCORD_CHANNEL_ID harus Anda simpan di GitHub Secrets
        run: node scripts/fetch_dq.js
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          # Pastikan path ini sesuai dengan struktur folder Anda
          OUT_PATH: public/dq.json
        
      - name: Check for changes
        id: git-diff
        run: |
          git diff --quiet public/dq.json || echo "HAS_CHANGES=true" >> $GITHUB_ENV
        
      - name: Commit and push changes
        if: env.HAS_CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update daily quest data"
          # Ganti ini dengan path file JSON Anda
          file_pattern: 'public/dq.json'

